name: Playwright Python Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://practicesoftwaretesting.com/
      USER_EMAIL: test@example.com
      USER_PASSWORD: password123
      CARD_NUMBER: 0000-0000-0000-0000
      CARD_EXPIRY: 10/2028
      CARD_CVV: 123
      CARD_NAME: Jack Howe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Python dependencies
        run: pip install -r TollShopApp/requirements.txt

      - name: Install Playwright browsers
        run: playwright install

      - name: Run tests
        run: pytest TollShopApp/Tests/purchase_products.py
